language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

install:
  - composer install --no-interaction --prefer-source

before_script:
  - touch database/database.sqlite
  - php artisan migrate

script: vendor/bin/phpunit
